### ISSUE TITLE
Look for potential template that we can use for the project

### ISSUE THREAD

**Issue by engramar** [codesydney/aicta#1]
I normally get templates from https://themeforest.net/
Make sure you are comfortable with the tech used, be it just bootstrap or even a Next.js template.

**Comment by ZizhangOu** [comment]
sure let me have a look ~ thx

**Comment by engramar** [comment]
Thanks @ZizhangOu

**Comment by engramar** [comment]
You may want to transition the status from 'Todo' to 'In progress'. 😊

**Comment by ZizhangOu** [comment]
> Thanks @ZizhangOu

I learned bootstrap before. I am going to learn nodejs soon.  And hope to finish next.js  through out the project.

**Comment by ZizhangOu** [comment]
![Image](https://user-images.githubusercontent.com/106296608/220453744-a3a9527b-d231-43ea-99ea-753d05b6dd09.png)

I can not edit the status is there any limitation for me editing the status

**Comment by engramar** [comment]
Apologies Kevin. I think I forgot to give you write access to the project. Please try again and let me know. Cheers.

**Comment by kaka5277** [comment]
goodmoring guys.i'm browering themeforest and going to learn some about bootstrap.Thank you very much.

**Comment by ZizhangOu** [comment]
https://themeforest.net/item/iteck-software-technology-html-template/38719600

https://iteck-html.themescamp.com/home-digital-agency.html

I think this will be enough for a brochure web, have a look

**Comment by engramar** [comment]
Thanks, @ZizhangOu. Looks perfect! Let me purchase this one now and send you the file shortly. Cheers!

**Comment by engramar** [comment]
Hello Guys, You can now find the template in https://drive.google.com/drive/folders/1RZUcf9ATsbGntePJVXWfOn0OPBsBs5zx?usp=sharing
Closing this issue now. Thanks.
